  # JMX2Insights Extension
  # ------------------------------------------
  # enabled: (true | false)
  # mode: (options - strict, open, promiscuous, disco)
  # frequency: (integer) value for harvest cycles in minutes
  # event_name: (string) the name of the custom event in Insights
  # mbean_n: (string) the mbean name and names of the attributes required
  # memory_events: (on | off) collects second by second memory details for jvm - generates 86400 events per day
  jmx2insights:
    enabled: true
    mode: strict
    frequency: 1
    beta_features: off
    event_name: JMX
    memory_events: off
    mbean_0: java.lang:type=Threading [ThreadCount,PeakThreadCount,DaemonThreadCount]
    mbean_1: java.lang:type=Compilation [TotalCompilationTime]
    mbean_2: java.lang:type=Runtime [Uptime]
    mbean_3: java.lang:type=GarbageCollector,name=ParNew [CollectionTime,CollectionCount]
    mbean_4: java.lang:type=GarbageCollector,name=ConcurrentMarkSweep [CollectionCount,CollectionTime]
    mbean_5: java.lang:type=GarbageCollector,name=MarkSweepCompact [CollectionCount,CollectionTime]
    mbean_6: java.lang:name=CMS Perm Gen,type=MemoryPool [CollectionUsage,CollectionUsageThreshold,CollectionUsageThresholdCount]    
    mbean_7: org.apache.jackrabbit.oak:type=RepositoryStats,name=Oak Repository Statistics [ObservationQueueMaxLength(tab_data_thingy|ANOTHER),attribute2(tab1|tab3),RegularAttrib]5
